Prefix: '&6[&aPlot&bSystem&6] &c>> &7'

MaxLower: 0
Title: false

DefaultFlags:
  - REDSTONE
  - FALL_DAMAGE
  - MOB_DAMAGE

PlotWorld: world

# Only works for own Claiming custom Blocks
MaxBlockClaim:
  Limited: true
  Amount: 12500000