name: PlotSystem
version: '${project.version}'
main: ch.framedev.plotsystem.main.Main
api-version: 1.17
authors: [ FrameDev ]
website: https://framedev.ch

commands:
  create:
  pos1:
  pos2:
  plot:
    aliases:
      - p
      - plots
      - plotsystem
  createplot:
  claim:
  pmarker:

permissions:
  plotsystem.*:
    children:
      plotsystem.admin.break: true
      plotsystem.admin.place: true
      plotsystem.admin.pvp: true
      plotsystem.admin.interact: true
      plotsystem.admin.ignore: true
  plotsystem.admin.break:
    default: op
  plotsystem.admin.place:
    default: op
  plotsystem.admin.pvp:
    default: op
  plotsystem.admin.interact:
    default: op
  plotsystem.admin.ignore:
    default: op