name: PlotSystem
version: '${project.version}'
main: ch.framedev.plotsystem.main.Main
description: Claim your own Blocks only for you, you can add Players to help you Build
api-version: '1.13'
authors: [ FrameDev ]
website: https://framedev.ch
softdepend:
  - Vault
  - SpigotMySQLUtils
  - SpigotSQLiteUtils

commands:
  create:
  pos1:
  pos2:
  plot:
    aliases:
      - p
      - plots
  createplot:
  claim:
  pmarker:
    description: Gives you the Marker for selecting your two Locations
  plotsystem:

permissions:
  plotsystem.*:
    children:
      plotsystem.admin.break: true
      plotsystem.admin.place: true
      plotsystem.admin.pvp: true
      plotsystem.admin.interact: true
      plotsystem.admin.ignore: true
      plotsystem.admin.create: true
      plotsystem.admin.createplot: true
      plotsystem.plot.marker: true
      plotsystem.plot.claim: true
      plotsystem.plot.visit: true
      plotsystem.plot.ban: true
      plotsystem.plot.flag: true
      plotsystem.plot.removeowner: true
      plotsystem.plot.setowner: true
      plotsystem.plot.removemember: true
      plotsystem.plot.addmember: true
      plotsystem.plot.info: true
      plotsystem.help: true
  plotsystem.admin.break:
    default: op
  plotsystem.admin.place:
    default: op
  plotsystem.admin.pvp:
    default: op
  plotsystem.admin.interact:
    default: op
  plotsystem.admin.ignore:
    default: op
  plotsystem.admin.create:
    default: op
  plotsystem.admin.createplot:
    default: op
  plotsystem.plot.marker:
    default: op
  plotsystem.plot.claim:
    default: op
  plotsystem.plot.visit:
    default: op
  plotsystem.plot.ban:
    default: op
  plotsystem.plot.flag:
    default: op
  plotsystem.removeowner:
    default: op
  plotsystem.plot.setowner:
    default: op
  plotsystem.plot.removemember:
    default: op
  plotsystem.plot.addmember:
    default: op
  plotsystem.plot.info:
    default: op
  plotsystem.help:
    default: op